% Compile the mex function 'writeVTK'
%
% Hints:
%  In order to figure out which C++ compiler is installed on your machine, use
%    mex -setup c++
%  Also possible:
%    myCompiler = mex.getCompilerConfigurations('C++','Selected')

%% Assuming VTK libraries have been installed using CMake

% vtkSrcPath = 'C:/MyProjects/VTK-src';
% vtkBinPath = 'C:/MyProjects/VTK-bin';
% vtkVersion = '7.1';
% 
% mex(['-I' vtkSrcPath '/Common/Core'], ...
%     ['-I' vtkBinPath '/Common/Core'], ...
%     ['-I' vtkSrcPath '/Common/Misc'], ...
%     ['-I' vtkBinPath '/Common/Misc'], ...
%     ['-I' vtkSrcPath '/Common/DataModel'], ...
%     ['-I' vtkBinPath '/Common/DataModel'], ...
%     ['-I' vtkSrcPath '/Common/ExecutionModel'], ...
%     ['-I' vtkBinPath '/Common/ExecutionModel'], ...
%     ['-I' vtkSrcPath '/IO/Core'], ...
%     ['-I' vtkBinPath '/IO/Core'], ...
%     ['-I' vtkSrcPath '/IO/Legacy'], ...
%     ['-I' vtkBinPath '/IO/Legacy'], ...
%     ['-I' vtkSrcPath '/IO/XML'], ...
%     ['-I' vtkBinPath '/IO/XML'], ...
%     ['-I' vtkSrcPath '/IO/PLY'], ...
%     ['-I' vtkBinPath '/IO/PLY'], ...
%     ['-I' vtkSrcPath '/IO/Geometry'], ...
%     ['-I' vtkBinPath '/IO/Geometry'], ...
%     ['-I' vtkSrcPath '/Utilities/KWIML'], ...
%     ['-I' vtkBinPath '/Utilities/KWIML'], ...
%     ['-L' vtkBinPath '/lib/Release'], ...
%     ['-lvtkCommonCore-' vtkVersion], ...
%     ['-lvtkCommonSystem-' vtkVersion], ...
%     ['-lvtkCommonMath-' vtkVersion], ...
%     ['-lvtkCommonMisc-' vtkVersion], ...
%     ['-lvtkCommonDataModel-' vtkVersion], ...
%     ['-lvtkCommonExecutionModel-' vtkVersion], ...
%     ['-lvtkCommonTransforms-' vtkVersion], ...
%     ['-lvtkIOCore-' vtkVersion], ...
%     ['-lvtkIOLegacy-' vtkVersion], ...
%     ['-lvtkIOXML-' vtkVersion], ...
%     ['-lvtkIOXMLParser-' vtkVersion], ...
%     ['-lvtkIOPLY-' vtkVersion], ...
%     ['-lvtkIOGeometry-' vtkVersion], ...
%     ['-lvtksys-' vtkVersion], ...
%     ['-lvtkexpat-' vtkVersion], ...
%     ['-lvtkzlib-' vtkVersion], ...
%     'writeVTK.cxx', ...
%     'additionalWriters/vtkOBJWriter.cxx', ...
%     'additionalWriters/vtkOFFWriter.cxx' ...
% );

%% Assuming VTK libraries have been installed using MacPorts

vtkIncPath = '/opt/local/include/vtk-7.1';
vtkLibPath = '/opt/local/lib';
vtkVersion = '7.1';

mex(['-I' vtkIncPath], ...
    ['-L' vtkLibPath], ...
    ['-lvtkCommonCore-' vtkVersion], ...
    ['-lvtkCommonDataModel-' vtkVersion], ...
    ['-lvtkCommonExecutionModel-' vtkVersion], ...
    ['-lvtkIOCore-' vtkVersion], ...
    ['-lvtkIOLegacy-' vtkVersion], ...
    ['-lvtkIOXML-' vtkVersion], ...
    ['-lvtkIOPLY-' vtkVersion], ...
    ['-lvtkIOGeometry-' vtkVersion], ...
    'writeVTK.cxx', ...
    'additionalWriters/vtkOBJWriter.cxx', ...
    'additionalWriters/vtkOFFWriter.cxx' ...
);
